# Generated by Django 3.1.5 on 2021-01-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0003_auto_20210106_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='recepti.recipe'),
        ),
    ]
