# Generated by Django 3.1.5 on 2021-01-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0004_auto_20210106_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='number',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='recepti.recipe'),
        ),
    ]
