# Generated by Django 3.1.5 on 2021-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0005_auto_20210106_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('5.0', 5), ('4.0', 4), ('3.0', 3), ('2.0', 2), ('1.0', 1)], max_length=20),
        ),
    ]
