# Generated by Django 3.1.5 on 2021-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0006_auto_20210106_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('5.0', '5.0'), ('4.0', '4.0'), ('3.0', '3.0'), ('2.0', '2.0'), ('1.0', '1.0')], max_length=20),
        ),
    ]
